---
title: "Untitled"
author: "Samuel Brown"
date: "2023-10-26"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
library(rvest)
library(xgboost)
library(tidyverse)
library(countrycode)
```

# Read in data
```{r, warning = FALSE}
gym <- rbind(read.csv("cleandata/data_2017_2021.csv"), read.csv("cleandata/data_2022_2023.csv")) %>% 
  unique() %>% 
  mutate(Name = str_to_title(paste(FirstName, LastName, sep = " ")),
         Country = countrycode( Country, 
                               origin = 'ioc', destination = 'country.name.en', 
                               custom_match = c("ROC" = "Russia", "IOM" = "Isle of Man", 
                                                "WAL" = "Wales", "ENG" = "England", 
                                                "SCO" = "Scotland", "SIN" = "Singapore", 
                                                "GE1" = "Germany", "NIR" = "Northern Ireland",
                                                "GE2" = "Germany", "JEY" = "Jersey", 
                                                "CCS" = "Guatemala", "EAI" = "Guatemala") )) 

head(gym)
```

##################################################################################################
# Get more data
### Gymter names, events, ages
```{r}
get_gymter_names <- function(url) {
  # Read the HTML content of the page
  page <- read_html(url)
  
  # Extract all links on the page along with their text content
  all_links <- page %>% html_nodes("a") %>% html_attr("href")
  all_names <- page %>% html_nodes("a") %>% html_text()
  
  # Create a data frame with links and names
  gymnast_data <- data.frame(Link = all_links, Name = all_names, stringsAsFactors = FALSE)
  
  return(gymnast_data)
}

# Example usage for the main page
gymter_names <- get_gymter_names("https://thegymter.net/gymnast-database/")
```

```{r, warning = FALSE}
get_gymter_events <- function(Names, Links) {
  # Initialize an empty data frame to store the results
  event_results <- data.frame(Name = character(), Date = character(), Competition = character(), 
                              Round = character(), Apparatus = character(), Score = numeric(), 
                              Birthday = character(), Gender = character(),
                              stringsAsFactors = FALSE)

  # Loop through each name and link
  for (i in seq_along(Names)) {
    name <- Names[i]
    link <- Links[i]

    tryCatch({
      # Try to read the HTML content
      link_html <- link %>% 
        read_html()
      
      # Get relevant years for dating the competition
      years <- link_html %>%
        html_nodes(xpath = '//*[@id="content"]//p/strong[contains(text(), "Results")]') %>%
        html_text() %>%
        str_extract("\\d+") %>%
        as.numeric() %>% 
        rev()

      # Extract the tables
      tables <- link_html %>%
        html_nodes(xpath = '//*[@id="content"]//table') %>%
        html_table(header = TRUE, na.strings = c("——", ""), convert = TRUE) %>% 
        rev()
      tables <- tables[1:length(years)]
      
      # Get birthday
      birthday <- link_html %>% 
        html_element(xpath = "/html/body/div[1]/div[2]/div[1]/div/article/div/table[1]/tbody/tr[3]/td[2]") %>%
        html_text()
      
      # Get country
      country <- link_html %>% 
        html_element(xpath = "/html/body/div[1]/div[2]/div[1]/div/article/div/table[1]/tbody/tr[2]/td[2]") %>% 
        html_text()

      # Combine the years and tables
      combined_data <- Map(cbind, Year = years, tables)

      # Bind all the tables into one
      result_table <- do.call(rbind, combined_data) %>% 
        rename(Round = Var.4)

      # Select relevant columns and update the Date column
      result_table <- result_table %>%
        mutate(across(VT:AA, ~ 
                        tryCatch(as.numeric(str_remove_all(as.character(.), "\\*$")), 
                                 error = function(e) NA)
                      )) %>%
        pivot_longer(cols = VT:AA, names_to = "Apparatus", values_to = "Score") %>% 
        mutate(Name = name,
               Date = paste(Date, Year, sep = " "),
               Birthday = birthday,
               Gender = 'w',
               Country = country) %>% 
        select(-Year)

      # Append the result, name, and link to the data frame
      event_results <- bind_rows(event_results, result_table)

    }, 
    # If it doesn't work, return NA
    error = function(e){
      return(NA)
    })
  }
  
  # Return the scraped data frame
  return(event_results)
}

gymter_events <- get_gymter_events(Names = gymter_names %>% slice(53:988) %>% pull(Name), 
                                   Links = gymter_names %>% slice(53:988) %>% pull(Link))
write.csv(gymter_events, file = "gymter_events.csv", row.names = FALSE)
```

### Get all links to Wikipedia performance pages
```{r}
get_olympic_links <- function(Years){
  # Make link_list
  link_list <- c()
  
  for (year in Years){
    # Make the proper Wikipedia URL
    url <- paste("https://en.wikipedia.org/wiki/Gymnastics_at_the_", year, "_Summer_Olympics",
                 sep = "")
    # Get all of the event results from that Olympics
    links <- url %>% 
      read_html() %>%
      html_nodes(xpath = '//*[@id="mw-content-text"]/div[1]/table[2]/tbody//a') %>%
      html_attr("href") %>%
      keep(~grepl(paste("/wiki/Gymnastics_at_the_", year, "_Summer_Olympics", sep = ""), .) & 
             (grepl("Men", .) | grepl("Women", .))) %>% 
      paste0("https://en.wikipedia.org", .)
    # Add to list of links
    link_list <- append(link_list, links)
  }
  return(link_list)
}

all_olympic_links <- get_olympic_links(seq(2008, 2020, by = 4))
```

### Wikipedia Olympic Results(Individual)
```{r}
# Function to get every type of individual result(qualifiers and finals) except all-around
scrape_indiv_olympic <- function(link){ 
  # Make useful functions for the future
  ### Check if it has numbers/scores
  has_numeric_columns <- function(df){
    any(sapply(df, is.numeric))
  }
  ### Check if a table has the right kind of scores
  new_scoring <- function(df){
    return(!any(colnames(df) %in% countrycode::codelist$country.name.en) & ("Total" %in% colnames(df))
           & !any(grepl("J[0-9]+", colnames(df))) & !any(grepl("Judge", colnames(df), ignore.case = TRUE))   )
  }
  ### Get ready to reassign column names
  reconcile_headers <- function(df) {
    header_row <- df[1, ]
    df <- df[-1, ]
    colnames(df) <- make.unique(make.names(header_row), sep = "_")
    return(df)
  }

  ##############################################################################
  ##### Getting the tables out
  # Read HTML content
  page <- read_html(link)

  # Extract tables
  tables <- page %>%
    html_nodes("table") %>%
    map(html_table, header = TRUE, fill = TRUE)
  
  # Turn the total score category into a numeric variable with a uniform name
  for (i in 1:length(tables)){
    table <- tables[[i]]
    
    if (  any(c("Rank", "Position", "Gymnast", "Name", "Nation", "Country", "Total") %in% table[1, ])  ){
      if("Total" %in% colnames(table)){
        tables[[i]] <- reconcile_headers(table) %>% 
          mutate(Total = suppressWarnings(as.numeric(Total)))
      } else if("Score" %in% colnames(table)){
        tables[[i]] <- reconcile_headers(table) %>% 
          mutate(Score = suppressWarnings(as.numeric(Score))) %>% 
          rename(Total = Score)
      }
    }
  }
  
  # Filter out tables that aren't useful
  tables_mask <- lapply(tables, has_numeric_columns)
  tables <- tables[unlist(tables_mask)]
  tables_mask <- lapply(tables, new_scoring)
  tables <- tables[unlist(tables_mask)]
  # Check if there are no more links
  if (length(tables) == 0){
    return(NA)
  } else {
  ##############################################################################
  ##### Cleaning and standardizing the tables
  # Find the apparatus from the link
  sport <- str_extract(link, "(?<=\\%27s_).*")
  event_mapping <- c(
    "balance_beam" = "BB",
    "vault" = "VT",
    "floor" = "FX",
    "uneven_bars" = "UB",
    "parallel_bars" = "PB",
    "horizontal_bar" = "HB",
    'pommel_horse' = "PH",
    'rings' = 'SR'
    )
  app_abbrev <- event_mapping[sport]
  
  # Find gender from the link
  link_str <- sub("%27s_.*$", "", link)
  full_gender <- sub(".+_", "", link_str)
  gender <- tolower(substr(full_gender, 1, 1))
  
  # Find the dates and assign based on how complete the information is
  year <- gsub(".*_(\\d{4}).*", "\\1", link)
  comp_dates <- read_html(link) %>% 
    html_nodes(".infobox-data") %>% 
    keep(grepl("August", .) | grepl("July", .) | grepl("September", .)) %>% 
    html_text() %>% 
    str_match_all("(\\d+\\s+\\w+(?:\\s+\\d{4})?)") %>% 
    unlist()
  if (is.null(comp_dates[1])){ 
    # If no dates given, assume early August
    qual_date <- paste("1 August", year) %>% dmy()
    final_date <- paste("1 August", year) %>% dmy()
  } else if (is.na(comp_dates[1])){
    # If no dates given, assume early August
    qual_date <- paste("1 August", year) %>% dmy()
    final_date <- paste("1 August", year) %>% dmy()
  } else if (1 + str_count(comp_dates[1] ,"\\W+") == 3){
    qual_date <- comp_dates[1] %>% dmy()
    final_date <- comp_dates[2] %>% dmy()
  } else if(1 + str_count(comp_dates[1] ,"\\W+") == 2){
    qual_date <- paste(comp_dates[1], year) %>% dmy()
    final_date <- paste(comp_dates[2], year) %>% dmy()
  } 
  
  # Go through each table and:
    # Get column names to match up
    # Fix the country column to be consistent
    # Fix the score column so it works and is numeric
    # Label as qualifier or gold medal round and add in the date
    # Label apparatus & gender & competition level
    # Standardize column names
  for (i in 1:length(tables)){
    table <- tables[[i]]
    # Make sure the Rank and Name columns are consistent 
    table <- table %>% 
      rename(Rank = 1, Name = 2) 
    # Make Country a column if not already in
    if (!('Nation' %in% colnames(table)) & !('Country' %in% colnames(table))){
      table <- table %>% 
        mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                     origin = 'ioc', destination = 'country.name.en', 
                                     custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
               Name = str_trim(str_remove_all(Name, "\\(.*?\\)"))) %>%
        relocate(Country, .after = Name)
    } else if('Nation' %in% colnames(table)){
        table <- table %>% 
          rename(Country = Nation)
      }
    
    # Fix score columns if it has non-numeric characters
    table <- table %>% 
      mutate(Total = as.numeric(gsub("[^0-9.]", "", Total)))

    # Change rank to be more accurate and label as final or qualifying round
    # Also add date
    table$Rank <- as.numeric(table$Rank)
    if (is.na(table[1, 'Rank'])){
      table$Round <- 'final'
      table$Date <- final_date
      table$Rank <- rank(-table$Total, ties.method = "min")
    } else{
      table$Round <- 'qual'
      table$Date <- qual_date
    }
    # Label apparatus and gender and Olympics
    table$Apparatus <- app_abbrev
    table$Gender <- gender
    table$Competition <- "Olympic Games"
    # Get consistent column names
    if (ncol(table) %in% c(17, 18)){
      table <- table %>% 
        rename(D_Score = 4, E_Score = 5, Penalty = 6, Score = 7,
               D_Score2 = 8, E_Score2 = 9, Penalty2 = 10, Score2 = 11) %>% 
        mutate(Penalty = abs(as.numeric(Penalty)) %>% suppressWarnings(),
               Penalty2 = abs(as.numeric(Penalty2)) %>% suppressWarnings()) %>% 
        select(Rank, Name, Country, D_Score, E_Score, Penalty, Score, 
               D_Score2, E_Score2, Penalty2, Score2,
               Total, Round, Date, Apparatus, Gender, Competition) %>% 
                slice(rep(1:n(), each = 2)) %>% 
        mutate(D_Score = ifelse(row_number() %% 2 == 0, D_Score2, D_Score) %>% as.numeric(),
               E_Score = ifelse(row_number() %% 2 == 0, E_Score2, E_Score) %>% as.numeric(),
               Penalty = ifelse(row_number() %% 2 == 0, Penalty2, Penalty) %>% as.numeric(),
               Total = ifelse(row_number() %% 2 == 0, Score2, Score) %>% as.numeric(),
               Apparatus = ifelse(
                 row_number() %% 2 == 0, 
                 paste(Apparatus, 2, sep = ""), paste(Apparatus, 1, sep = ""))) %>% 
        select(-D_Score2:-Score2, -Score)
      
      grouped_table <- table %>% 
        group_by(Rank, Name, Country, Round, Date, Gender, Competition) %>% 
        summarize(D_Score = mean(D_Score, na.rm = TRUE), 
                  E_Score = mean(E_Score, na.rm = TRUE), 
                  Penalty = mean(Penalty, na.rm = TRUE), 
                  Total = mean(Total, na.rm = TRUE),
                  Apparatus = app_abbrev,
                  .groups = "drop")
      
      table <- bind_rows(table, grouped_table)

    } else if(ncol(table) %in% c(12, 13)){
      table <- table %>% 
        rename(D_Score = 4, E_Score = 5, Penalty = 6) %>% 
        mutate(Penalty = abs(as.numeric(Penalty)) %>% suppressWarnings()) %>% 
        select(Rank, Name, Country, D_Score, E_Score, Penalty, 
               Total, Round, Date, Apparatus, Gender, Competition)
    }
    
    # Put the modified table back into the list
    tables[[i]] <- table %>% 
      rename(Score = Total)
  }
  
  # Return the list of tables
  return(tables)
  }
}
```

```{r}
# Function to get individual all-around Olympics
scrape_aa_olympic <- function(links){
  ##### Make function(s) for later
  # Checks for score tables
  has_relevant_columns <- function(df){
    return(  ("Gymnast" %in% colnames(df)) & ("Total" %in% colnames(df))  )
  }
  ##############################################################################
  ##### Getting the correct tables and putting some link-specific data in
  tables <- list()
  for (link in links){
    # Find gender from the link
    link_str <- sub("%27s_.*$", "", link)
    full_gender <- sub(".+_", "", link_str)
    gender <- tolower(substr(full_gender, 1, 1))
    # Find the dates and assign based on how complete the information is
    year <- gsub(".*_(\\d{4}).*", "\\1", link)
    comp_dates <- read_html(link) %>% 
      html_nodes(".infobox-data") %>% 
      keep(grepl("August", .) | grepl("July", .) | grepl("September", .)) %>% 
      html_text() %>% 
      str_match_all("(\\d+\\s+\\w+(?:\\s+\\d{4})?)") %>% 
      unlist()
    if (is.null(comp_dates[1])){ 
     # If no dates given, assume early August
      qual_date <- paste("1 August", year) %>% dmy()
      final_date <- paste("1 August", year) %>% dmy()
    } else if (is.na(comp_dates[1])){
      # If no dates given, assume early August
      qual_date <- paste("1 August", year) %>% dmy()
      final_date <- paste("1 August", year) %>% dmy()
    } else if (1 + str_count(comp_dates[1] ,"\\W+") == 3){
      qual_date <- comp_dates[1] %>% dmy()
      final_date <- comp_dates[2] %>% dmy()
    } else if (1 + str_count(comp_dates[1] ,"\\W+") == 2){
      qual_date <- paste(comp_dates[1], year) %>% dmy()
      final_date <- paste(comp_dates[2], year) %>% dmy()
    }     
    
    # Get all of that link's tables out
    link_tables <- read_html(link) %>% 
      html_nodes("table") %>% 
      map(html_table, header = TRUE, fill = TRUE)
    # Filter them for the ones that have the right column names
    tables_mask <- lapply(link_tables, has_relevant_columns)
    link_tables <- link_tables[unlist(tables_mask)]
    ##############################################################################
    ##### Cleaning and standardizing the tables
    for (i in 1:length(link_tables)){
      table <- link_tables[[i]]
      first_col_name <- colnames(table)[1]
      # Standardize column names and then clean
      if ("Prelim" %in% colnames(table)){
        if(("Prelim" %in% colnames(table)) & (gender == "m")){
          colnames(table) <- c("Rank", "Name", "Country", "Prelim", "FX", "PH", "SR", "VT", "PB", "HB", "AA")
        } else if(("Prelim" %in% colnames(table)) & (gender == "w")){
          colnames(table) <- c("Rank", "Name", "Country", "Prelim", "VT", "UB", "BB", "FX", "AA")
          table <- table %>% relocate(FX, .before = VT)
        }
        # Add qualifying scores in if they don't have their own table
        link_tables[[length(link_tables) + 1]] <- table %>% 
          select(Name, Country, Prelim) %>% 
          mutate(Apparatus = "AA",
                 Rank = min_rank(desc(Prelim)),
                 Gender = gender,
                 Date = final_date,
                 Competition = "Olympic Games",
                 Round = "qual") %>% 
          rename(Score = Prelim)
        # Add in each individual's final apparatus performance plus total performance
        table <- table %>% 
          select(-Prelim) %>% 
          filter(!grepl("Did not advance", SR)) %>% 
          mutate(across(FX:AA, ~ str_extract(., "^[^\\(]+") %>% as.numeric() %>% suppressWarnings()),
                 Rank = min_rank(desc(AA)),
                 Gender = gender,
                 Date = final_date,
                 Competition = "Olympic Games") %>% 
          pivot_longer(cols = FX:AA,
                       names_to = "Apparatus",
                       values_to = "Score") %>% 
          mutate(Round = ifelse(Apparatus != "AA", "AAfinal", "final"))   

      } else if(!(is.na(table[1, as.name(first_col_name)])) & (table[1, as.name(first_col_name)] != "")){
        if((gender == "m") & (("Nation" %in% colnames(table)) | ("Country" %in% colnames(table)))){
          colnames(table) <- c("Rank", "Name", "Country", "FX", "PH", "SR", "VT", "PB", "HB", "AA", "Notes")
        } else if(gender == "m"){
          colnames(table) <- c("Rank", "Name", "FX", "PH", "SR", "VT", "PB", "HB", "AA", "Notes")
          table <- table %>% 
            mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                          origin = 'ioc', destination = 'country.name.en', 
                                          custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                   Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
        } else if((gender == "w") & (("Nation" %in% colnames(table)) | ("Country" %in% colnames(table)))){
          colnames(table) <- c("Rank", "Name", "Country", "VT", "UB", "BB", "FX", "AA", "Notes")
          table <- table %>% relocate(FX, .before = VT)
        } else if(gender == "w"){
          colnames(table) <- c("Rank", "Name", "VT", "UB", "BB", "FX", "AA", "Notes")
          table <- table %>% 
            relocate(FX, .before = VT) %>% 
            mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                          origin = 'ioc', destination = 'country.name.en', 
                                          custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                   Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
        }
        # Add in each individual's qualifying apparatus performance plus total qualifying performance
        if ("Notes" %in% colnames(table)){
          table <- table %>% select(-Notes)
        }
        table <- table %>% 
          mutate(across(FX:AA, ~ str_extract(., "^[^\\(]+") %>% as.numeric() %>% suppressWarnings()),
                 Rank = min_rank(desc(AA)),
                 Gender = gender,
                 Date = final_date,
                 Competition = "Olympic Games") %>% 
          pivot_longer(cols = FX:AA,
                       names_to = "Apparatus",
                       values_to = "Score") %>% 
          mutate(Round = ifelse(Apparatus != "AA", "AAqual", "qual"))
      } else {
        if((gender == "m") & (("Nation" %in% colnames(table)) | ("Country" %in% colnames(table)))){
          colnames(table) <- c("Rank", "Name", "Country", "FX", "PH", "SR", "VT", "PB", "HB", "AA", "Notes")
        } else if((gender == "m")){
          colnames(table) <- c("Rank", "Name", "FX", "PH", "SR", "VT", "PB", "HB", "AA", "Notes")
          table <- table %>% # Get country/nation info if it isn't in there already
            mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                          origin = 'ioc', destination = 'country.name.en', 
                                          custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                   Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
        } else if((gender == "w") & ("Nation" %in% colnames(table)) | ("Country" %in% colnames(table))){
          colnames(table) <- c("Rank", "Name", "Country", "VT", "UB", "BB", "FX", "AA", "Notes")
          table <- table %>% relocate(FX, .before = VT)
        } else if((gender == "w")){
          colnames(table) <- c("Rank", "Name", "VT", "UB", "BB", "FX", "AA", "Notes")
          table <- table %>% 
            relocate(FX, .before = VT) %>% 
            mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                          origin = 'ioc', destination = 'country.name.en', 
                                          custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                   Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
        }
        # Add in each individual's final apparatus performance plus total final performance
        table <- table %>% 
          mutate(across(FX:AA, ~ str_extract(., "^[^\\(]+") %>% as.numeric() %>% suppressWarnings()),
                 Rank = min_rank(desc(AA)),
                 Gender = "m",
                 Date = final_date,
                 Competition = "Olympic Games") %>% 
          pivot_longer(cols = FX:AA,
                       names_to = "Apparatus",
                       values_to = "Score") %>% 
          mutate(Round = ifelse(Apparatus != "AA", "AAfinal", "final"))   
      }
      
      link_tables[[i]] <- table
    }
    
    # Append that to the table list
    tables <- append(tables, link_tables)
  }
  ##############################################################################
  return(tables %>% bind_rows())
}
```

```{r, WARNING = FALSE}
# Scrape all Olympic individual events from Wikipedia
indiv_olympic_events <- all_olympic_links %>% 
  keep(grepl("vault", .) | grepl("floor", .) | grepl("pommel_horse", .) | grepl("rings", .) | 
         grepl("parallel_bars", .) | grepl("uneven_bars", .) | grepl("balance_beam", .) | 
         grepl("horizontal_bar", .)) %>% 
  map(scrape_indiv_olympic) %>% 
  purrr::list_flatten() %>% 
  keep(.p = !is.na(.)) 
aa_olympic_events <- all_olympic_links %>% 
  keep(grepl("artistic_individual_all-around", .)) %>% 
  scrape_aa_olympic() 


aa_olympic_events %>% 
  # bind_rows() %>% 
  filter(is.na(Score))


write.csv(bind_rows(indiv_olympic_events, aa_olympic_events), 
          file = "indiv_olympic_events.csv", 
          row.names = FALSE)
```

### Wikipedia Olympic Results(Team)
```{r}
# Function to scrape team final results
scrape_team_finals <- function(links){
  ##############################################################################
  ##### Getting the correct tables and putting some link-specific data in
  tables <- list()
  for (link in links){
    # Read HTML content
    page <- read_html(link)
    # Extract tables
    link_tables <- page %>%
      html_nodes("table") %>%
      map(html_table, header = TRUE, fill = TRUE)
    # Find gender from the link
    link_str <- sub("%27s_.*$", "", link)
    full_gender <- sub(".+_", "", link_str)
    gender <- tolower(substr(full_gender, 1, 1))
    # Find the year of the link
    year <- gsub(".*_(\\d{4}).*", "\\1", link)
    
    # Get to the correct tables
    if ((gender == "m" & year == "2008") | 
        (gender == "w" & year == "2012") |
        (year == "2016")){
      table <- link_tables[[5]]
    } else if (gender == "m" & year == "2012"){
      table <- link_tables[[4]]
    } else if (year == "2020" | 
               gender == "w" & year == "2008"){
      table <- link_tables[[6]]
    }
    ##############################################################################
    ##### Cleaning and standardizing the tables
    # Get score/rank columns straight
    if (gender == "w"){
      if (year == "2016"){
        table <- table[, 1:7]
      }
      colnames(table) <- c("Rank", "Name", "VT", "UB", "BB", "FX", "AA")
      table <- table[table$Name != "",]
      table <- table %>%
        mutate(across(c(VT, UB, BB, FX), list(
          Score = ~as.numeric(str_remove_all(str_extract(.x, "^[^\\s(]+"), "[()]")),
          Rank = ~as.numeric(str_remove_all(str_extract(.x, "\\((.*?)\\)"), "[()]"))
            )),
          AA_Score = if_else(is.na(FX_Rank), NA_real_, AA),
          AA_Rank = min_rank(desc(AA))) %>%
        select(-VT:-FX, -Rank, -AA)
      
    } else if (year == "2008" | year == "2020"){
      colnames(table) <- c("Rank", "Name", "FX", "PH", "SR", "VT", "PB", "UB", "AA")
      table <- table %>% 
        mutate(across(c(FX, PH, SR, VT, PB, UB), list(
          Score = ~as.numeric(str_remove_all(str_extract(.x, "^[^\\s(]+"), "[()]")),
          Rank = ~as.numeric(str_remove_all(str_extract(.x, "\\((.*?)\\)"), "[()]"))
            )),
          AA_Score = if_else(is.na(FX_Rank), NA_real_, AA),
          AA_Rank = min_rank(desc(AA))) %>% 
        select(!(FX:UB), -Rank, -AA) 
    } else {
      colnames(table) <- c("Name", "FX_Score", "FX_Rank", "PH_Score", "PH_Rank", "SR_Score", 
                           "SR_Rank", "VT_Score", "VT_Rank", "PB_Score", "PB_Rank", "UB_Score", 
                           "UB_Rank", "AA_Score", "AA_Rank")
      table <- table[-1, ]
      table <- table[table$Name != "",]
      
      table <- table %>% 
        mutate(across(FX_Score:AA_Rank, as.numeric),
               AA_Rank = min_rank(desc(AA_Score)))
    }
    # Fix name and country columns
    if ((gender == "w" & year == "2012") |
        (year == "2008")){
      table <- table %>% 
        mutate(Country = ifelse(Name %in% c(codelist$country.name.en, "ROC"),
                                Name,
                                NA),
               .after = Name) %>%
        fill(Country)
    } else {
      table <- table %>%
        mutate(Country = ifelse(Name %in% c(codelist$country.name.en, "ROC"),
                                Name,
                                NA),
               .after = Name,
               Name = str_trim(str_remove_all(Name, "\\(.*?\\)"))) %>% 
        fill(Country)
    }
    # Select correct columns, then pivot to long format and remove incomplete rows
    if (gender == "w"){
      table <- table %>% 
        select(Name, Country, starts_with(c("VT", "UB", "BB", "FX", "AA"))) %>% 
        pivot_longer(cols = VT_Score:AA_Rank,
             names_to = c("Apparatus", ".value"),
             names_pattern = "(.*)_(.*)",
             values_to = c("Score", "Rank")) %>% 
        drop_na(Name, Score)
    } else {
      table <- table %>% 
        select(Name, Country, starts_with(c("FX", "PH", "SR", "VT", "PB", "UB", "AA"))) %>% 
        pivot_longer(cols = FX_Score:AA_Rank,
                     names_to = c("Apparatus", ".value"),
                     names_pattern = "(.*)_(.*)",
                     values_to = c("Score", "Rank"))    %>% 
        drop_na(Name, Score)
    }
    # Add in extra info
    table <- table %>% 
      mutate(Gender = gender,
             Competition = "Olympic Games",
             Round = "TeamFinal",
             Date = paste("August 1", year) %>% mdy())
    
    # Save this in the overall list
    tables <- append(tables, list(table))
  }
  # Return the results
  return(tables)
}
```

```{r}
# Function to scrape team qualifications
scrape_team_quals <- function(links){
  # Get the first row to become the column names
  reconcile_headers <- function(df) {
    header_row <- df[1, ]
    df <- df[-1, ]
    colnames(df) <- make.unique(make.names(header_row), sep = "_")
    return(df)
  }
  # Make function to find the right table
  valid_table <- function(df){
    return( any(grepl("All-around", colnames(df))) )
  }
  ##############################################################################
  ##### Getting the tables out
  table_list <- list()
  
  for (link in links){
    # Read HTML content
    page <- read_html(link)
    # Extract tables
    link_tables <- page %>%
      html_nodes("table") %>%
      map(html_table, header = TRUE, fill = TRUE)
    # Find gender from the link
    link_str <- sub("%27s_.*$", "", link)
    full_gender <- sub(".+_", "", link_str)
    gender <- tolower(substr(full_gender, 1, 1))
    # Find the dates and assign based on how complete the information is
    year <- gsub(".*_(\\d{4}).*", "\\1", link)
    comp_dates <- read_html(link) %>% 
      html_nodes(".infobox-data") %>% 
      keep(grepl("August", .) | grepl("July", .) | grepl("September", .)) %>% 
      html_text() %>% 
      str_match_all("(\\d+\\s+\\w+(?:\\s+\\d{4})?)") %>% 
      unlist()
    if (is.null(comp_dates[1])){ 
     # If no dates given, assume early August
      qual_date <- paste("1 August", year) %>% dmy()
      final_date <- paste("1 August", year) %>% dmy()
    } else if (is.na(comp_dates[1])){
      # If no dates given, assume early August
      qual_date <- paste("1 August", year) %>% dmy()
      final_date <- paste("1 August", year) %>% dmy()
    } else if (1 + str_count(comp_dates[1] ,"\\W+") == 3){
      qual_date <- comp_dates[1] %>% dmy()
      final_date <- comp_dates[2] %>% dmy()
    } else if (1 + str_count(comp_dates[1] ,"\\W+") == 2){
      qual_date <- paste(comp_dates[1], year) %>% dmy()
      final_date <- paste(comp_dates[2], year) %>% dmy()
    }
    
    # Filter out tables that aren't useful
    tables_mask <- lapply(link_tables, valid_table)
    link_tables <- link_tables[unlist(tables_mask)]
    link_tables <- lapply(link_tables, reconcile_headers)
    ##############################################################################
    ##### Clean tables and extract info
    for(i in 1:length(link_tables)){
      table <- link_tables[[i]]
      
      # Assign column names(different for gender of competition)
      if (gender == "m"){
        if (!("Nation" %in% colnames(table))){
        colnames(table) <- c("Name", "FX_Score", "FX_Rank", "PH_Score", "PH_Rank", 
                             "SR_Score", "SR_Rank", "VT_Score", "VT_Rank", "PB_Score", "PB_Rank",
                             "UB_Score", "UB_Rank", "AA_Score", "AA_Rank")
          table <- table %>% 
            slice(-1) %>% 
            mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                          origin = 'ioc', destination = 'country.name.en', 
                                          custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                   .after = Name,
                   Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
        } 
        colnames(table) <- c("Name", "Country", "FX_Score", "FX_Rank", "PH_Score", "PH_Rank", 
                             "SR_Score", "SR_Rank", "VT_Score", "VT_Rank", "PB_Score", "PB_Rank",
                             "UB_Score", "UB_Rank", "AA_Score", "AA_Rank")
        
      } else if (gender == "w"){
        colnames(table) <- c("Name", "VT_Score", "VT_Rank", "UB_Score", "UB_Rank", 
                             "BB_Score", "BB_Rank", "FX_Score", "FX_Rank", "AA_Score", "AA_Rank")
        table <- table %>%
          mutate(Country = countrycode( str_remove_all(str_extract(Name, "\\((.*?)\\)"), "[()]"), 
                                        origin = 'ioc', destination = 'country.name.en', 
                                        custom_match = c("ROC" = "Russia") ) %>% suppressWarnings(),
                 .after = Name,
                 Name = str_trim(str_remove_all(Name, "\\(.*?\\)")))
      }
      
      # Change table to be in the proper format
      table <- table %>% 
        pivot_longer(cols = -c(Name, Country),
                     names_to = c("Apparatus", ".value"),
                     names_sep = "_") %>% 
        filter(Score != "—") %>% 
        mutate(Score = as.numeric(Score) %>% suppressWarnings(),
               Rank = str_extract(Rank, "\\d+") %>% as.numeric(),
               Gender = gender,
               Date = final_date,
               Competition = "Olympic Games",
               Round = "TeamQual")
      
      # Make one dataframe for countries only
      link_tables[[length(link_tables) + 1]] <- table %>% 
        filter(Name %in% codelist$country.name.en)
      
      # Make one dataframe for gymnasts
      table <- table %>% 
        filter(!(Name %in% codelist$country.name.en))
      
      link_tables[[i]] <- table
    }
    
    # Append that to the table list
    table_list <- append(table_list, link_tables)
  }
  
  ##############################################################################
  ##### Return valid tables all in one
  return(table_list %>% bind_rows())
}
```

```{r}
team_olympic_finals <- all_olympic_links %>% 
  keep(grepl("artistic_team", .)) %>%
  scrape_team_finals() %>% 
  bind_rows() %>% 
  suppressWarnings()

team_olympic_quals <- all_olympic_links %>% 
  keep(grepl("artistic_qualification", .)) %>% 
  scrape_team_quals()

write.csv(bind_rows(team_olympic_finals, team_olympic_quals), 
          file = "team_olympic_events.csv", 
          row.names = FALSE)
```


